### ISSUE TITLE
Dependency on Commons IO?

### ISSUE THREAD

**Issue by mrg** [tynamo/tapestry-security#20]
While upgrading from Tapestry 5.3 to 5.4, I updated Tynamo's Tapestry Security to version 0.6.2, but when running I received:

```
org.apache.shiro.subject.ExecutionException: java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:385)
	at org.tynamo.security.services.impl.SecurityConfiguration.service(SecurityConfiguration.java:54)
```

Adding the following to my pom.xml fixed the issue:

```
<dependency>
	<groupId>commons-io</groupId>
	<artifactId>commons-io</artifactId>
	<version>2.4</version>
</dependency>
```

Does Tynamo's Tapestry Security have a missing dependency?

Thanks!

**Comment by kaosko** [comment]
No, neither Shiro nor tapestry-security has a direct dependency on commons-io. Note that the error given is not ClassNotFoundException but NoClassDefFoundError. Certainly there's some code (perhaps a filter?) that requires commons-io but before your upgrade, it's likely that some library pulled in commons-io so you didn't notice it was needed. Check your dependency graph and compare versions before & after the upgrade.
