### ISSUE TITLE
REMEMBERME_CIPHERKERY constant name incorrectly spelt

### ISSUE THREAD

**Issue by timcu** [tynamo/tapestry-security#53]
In org.tynamo.security.SecuritySymbols, the variable name is spelt incorrectly. There should be no "R" in "KEY". 

public static final String REMEMBERME_CIPHERKERY = "security.remembermecipherkey";

You could also consider adding underscores between each word so it becomes REMEMBER_ME_CIPHER_KEY. You probably need to deprecate existing constant and add new one with correct spelling to prevent breaking existing code.

**Comment by kaosko** [comment]
Fixed
