### ISSUE TITLE
SAML with Okta support

### ISSUE THREAD

**Issue by cardaddy** [tynamo/tapestry-security#55]
Hi Kalle, I'm using a couple older versions of Tapestry, 5.4.3 and an older 5.3 that can't be upgraded. In my 5.4.3 I'm using Tapestry-Security 0.6.6 and need to integrate with Okta using SAML with SSO. Any thoughts on how I might be able to achieve this?

**Comment by kaosko** [comment]
It's been years I last worked with SAML but on a high level, it's just different messaging protocol. I've used buji-pac4j w/ Shiro before, although not with SAML. I might look into it first.

**Comment by cardaddy** [comment]
I'm looking at buji-pac4j now and I'm a bit lost with integrating with tapestry-security. Btw, the corporate goal is to just be able to provide SSO through the okta portal. Is this something that could be done with OpenID rather than SAML?

**Comment by kaosko** [comment]
You need tynamo-federatedaccounts (http://www.tynamo.org/tynamo-federatedaccounts+guide/), actually there's already a Pac4jFederatedRealm implementation which may or may not work for you. It's considerably easier if you just need to integrate with a single provider/protocol. In any case, follow the examples. For the latter, I'd assume so but never used okta.

**Comment by cardaddy** [comment]
Do you do any contracting work on the side where you could help us with this integration?
