### ISSUE TITLE
Does not work with tapestry 5.7.0

### ISSUE THREAD

**Issue by andriassundskard** [tynamo/tapestry-security#57]

**Comment by kaosko** [comment]
Thanks, should have check already. But perhaps you can give me a description of what fails and when?

**Comment by andriassundskard** [comment]
Sure!

I get a compile error in the following line after upgrading tapestry to 5.7.0.

`configuration.add("page", factory.createChain("/page*/**").add(factory.anon()).build());`

**Comment by andriassundskard** [comment]
I have edited the comment above to give more info. Hopefully this helps!

**Comment by kaosko** [comment]
Closing, tapestry-security 0.9.0 release for T5.7.x will follow shortly.
