### ISSUE TITLE
0.8.0 and 0.9.0 Pulling in wrong depencencies

### ISSUE THREAD

**Issue by cardaddycom** [tynamo/tapestry-security#63]
I'm trying to use this library with Tap 5.8, but it for some odd reason when I grab either 0.8.0 or 0.9.0 they both pull in tap core 5.5, tap ioc 5.5 and shiro 1.0.3 ultimately causing Caused by: java.lang.ClassNotFoundException: org.apache.tapestry5.ioc.MappedConfiguration.

**Comment by kaosko** [comment]
You can override dependencies as needed but there are some updates needed for T5.8 compatibility, I'll take a look at it.
