### ISSUE TITLE
Session timeout, Login, POST form resubmission fails

### ISSUE THREAD

**Issue by balapal** [tynamo/tapestry-security#7]
If I leave a page open (annotated with '''@RequiresUser''') with a form on it and submit the form after session timed out then I get redirected to the login page.
On successful login the form submission is attempted again, but it fails with the following error: _Forms require that the request method be POST and that the t:formdata query parameter have values._

**Comment by kradhakr** [comment]
This is regarding the compatibility of Java 8 with Tapestry 3.0.3. We have an application which is built in Java 6 and Tapestry 3.0.3.
While upgrading the application to Java 8, we got the below error.

[Error] Unable to resolve expression 'tableRowsIterator' for org.apache.tapestry.contrib.table.components.TableRows$Enhance_45@19a5b30[MyCalculations/table.tableRows].
org.apache.tapestry.BindingException: Unable to resolve expression 'tableRowsIterator' for org.apache.tapestry.contrib.table.components.TableRows$Enhance_45@19a5b30[MyCalculations/table.tableRows].
                at org.apache.tapestry.binding.ExpressionBinding.resolveProperty(ExpressionBinding.java:205)

Just wanted to check if it is really possible to upgrade the application to Java 8 with Tapestry 3.0.3.

**Comment by kaosko** [comment]
Huh @kradhakr? Totally wrong place, you added a comment on unrelated issue that was closed two years ago and on top of that, Tynamo never supported Tapestry 3.x.

**Comment by kradhakr** [comment]
OK.Can you tell me who can help in this?
